server:
  port: 9001
spring:
  application:
    name: nacos-customers-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 192.168.0.3:8888
  datasource:
    url: jdbc:mysql://localhost:3306/sql_store?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 0
    driver-class-name: com.mysql.cj.jdbc.Driver
management:
  endpoints:
    web:
      exposure:
        include: '*'
 # thymeleaf:
 #   prefix: classpath:/statics/
 #   suffix: .html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# type-Enums-Package: com/lihoulai/demo/enums